### ISSUE TITLE
Version var in config files

### ISSUE THREAD

**Issue by AndreiIgna** [shivas/versioning-bundle#44]
I'm using this bundle, which is really helpful 👍🏼

I want to add the version number to assets, which needs to be configured like this:
```yaml
# config/packages/framework.yaml
framework:
    # ...
    assets:
        version: 'v2'
        version: '%shivas_versioning.version%'
```

Is the version number available to use in config files? I haven't seen any info related to this, and after trying a few variable names couldn't make it work..

If it's not available for config files yet, would be a useful feature
